---
- name: autoreconf shairport-sync
  command: autoreconf -i -f chdir={{ home }}/.build/shairport-sync

- name: configure shairport-sync
  command: ./configure --with-configfiles --with-avahi --with-alsa --with-ao --with-ssl=openssl --with-systemd chdir={{ home }}/.build/shairport-sync

- name: build shairport-sync
  make: chdir={{ home }}/.build/shairport-sync

- name: install shairport-sync
  make: target=install chdir={{ home }}/.build/shairport-sync
  become: yes

- name: enable shairport-sync service
  systemd: name=shairport-sync state=started enabled=yes daemon_reload=yes
  become: yes
