---
- name: install media tools via apt
  apt:
    state: present
    pkg:
      - libav-tools
      - mplayer
  become: yes
  tags: media-tools

- name: install media tools via pip
  pip:
    state: present
    name:
      - youtube-dl
  become: yes
  tags: media-tools
