---
- name: update apt cache
  apt: update_cache=yes
  become: yes

- name: upgrade safe packages
  apt: upgrade=safe
  become: yes

- name: install essential tools
  apt:
    state: present
    pkg:
      - build-essential
      - curl
      - git
      - gettext
      - htop
      - iftop
      - iotop
      - sudo
      - vim
  become: yes
